### ISSUE TITLE
[Messages] Show relevant info

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#103]
Show relevant info in the messages table
- name 
- phone
- message text
- sent date
- is message read

**Comment by ghefraim** [comment]
Coding done, can be tested in PROD @ddardistrugatoru

**Comment by ddardistrugatoru** [comment]
works, one thing you can do it s to add a character limit for the message input. look into prod at message tab so you can understand why

**Comment by ghefraim** [comment]
Creating a ticket. Will do later. #namchefacuma
