### ISSUE TITLE
Functionalitate inscriere

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#14]
Owner: me
Help: @MaxiFrancis 

This is the user signup flow:
https://drive.google.com/file/d/1CU5OvePvt1dskA8JSNikM_uPd2bI9P2U/view?usp=drive_link
![image](https://github.com/ghefraim/hopecamp-website/assets/92709351/6b308c3e-33f2-44b9-ac77-67c8e85af863)

Details about user (form fields) will be coming soon.

**Comment by MaxiFrancis** [comment]
[Components.pdf](https://github.com/ghefraim/hopecamp-website/files/14874397/Components.pdf)
Components to create

**Comment by ghefraim** [comment]
Required fields for the user:
- Id
- EmailAddress 
- FullName
- Age
- Phone - nr de tel 
- Church - biserica din care provin
- PayTaxTo - taxa de inscriere o platesc la
- AmountPaid
- Transport - mijloc de transport
- StartDate - data in care vin in tabara
- EndDate  - data in care plec din tabara
- ImageUrl - imaginea cu persoana
- IsAdmin (bool) - true, if has admin access
- IsConfirmed (bool) - true if confirmat in tabara de catre admini
- Preferences *can be null or empty - prefferinte cazare
- SignupDate

**Comment by ghefraim** [comment]
Security concern: 
It's okay to have the Firebase values exposed in the code, but we need to make sure we set proper rules as per this thread:
https://stackoverflow.com/questions/75290749/is-it-insecure-and-bad-practice-to-expose-your-environment-variables-to-the-brow

**Comment by ghefraim** [comment]
Remaining tasks:

- [ ] Implement the 'personal details' form (step 2) in the MultiStepForm @MaxiFrancis 
- [ ] Add details in database @ghefraim 
- [ ] Properly handle user context (redirect based on status) @ghefraim  
- [ ] Fix TODOs from code @MaxiFrancis

**Comment by MaxiFrancis** [comment]
For auth, we will use just email auth? Because firebase allows us to use also google auth, phone number auth..
Will we use more types or will stick just to email?

**Comment by ghefraim** [comment]
That's a fair question.
For now we we only use email/password for authentication.

The reason is that we want to do authentication and store the user in the db at the same time.
If we use 3rd party providers, we'd have to separate these 2 steps, introducing more complexity, for us as devs, and for the user experience.

**Comment by MaxiFrancis** [comment]
> Remaining tasks:
> 
> * [ ]  Implement the 'personal details' form (step 2) in the MultiStepForm @MaxiFrancis


I do not really understand this step.
So here might come this list?
Id
EmailAddress
FullName
Age
Phone - nr de tel
Church - biserica din care provin
PayTaxTo - taxa de inscriere o platesc la
AmountPaid
Transport - mijloc de transport
StartDate - data in care vin in tabara
EndDate - data in care plec din tabara
ImageUrl - imaginea cu persoana
IsAdmin (bool) - true, if has admin access
IsConfirmed (bool) - true if confirmat in tabara de catre admini
Preferences *can be null or empty - prefferinte cazare
SignupDate
 
 Or this is a login for user, and the fields above will be singn up forms for users that can be logged in with their account, to register to that season camp?
