### ISSUE TITLE
[Index] Code landing page based on design

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#36]
based on the [figma file ](https://www.figma.com/file/EgK4edNYC3RxzK7OEq3vVV/hopecamp.ro?type=design&node-id=0-1&mode=design&t=RitzhEZuIkgYxXdr-0)start coding the index page

**Comment by ghefraim** [comment]
@DenisWithOneN everything on track?

**Comment by DenisWithOneN** [comment]
> @DenisWithOneN everything on track?

Working on it, we should talk to Filip about the rest of the design, right now I only have the mobile index in the Figma file

**Comment by ghefraim** [comment]
Can you just try to guess what would be the best option? I think we don't have time to ask for another design.

**Comment by DenisWithOneN** [comment]
Worst case I keep the mobile design for the most part of the index page, changing the sizes for tablet/desktop view. For simpler sections I can temporarily change the layout from one column to two columns until we get the updated design

**Comment by ghefraim** [comment]
I agree. I think we can go on with this one

**Comment by ghefraim** [comment]
@DenisWithOneN I think we're missing an "Descarca regulament" button in the design. Please add it somewhere near the "interbari frecvente" section.

When it's clicked, the file "Regulament_HopeCamp.pdf" should be downloaded. We'll get this pdf file next week. Until then, use a placeholder file.

**Comment by ddardistrugatoru** [comment]
https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/6ee44b99-9629-48f6-9e44-6cded478e7c6

**Comment by ddardistrugatoru** [comment]
![440951675_970029758170515_8874617223963904968_n](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/8105c6b8-067c-4ad7-a967-9b14609d74fa)

**Comment by DenisWithOneN** [comment]
The video is not on the white spot on purpose, the Figma design suggested it. But if you guys think it looks bad we can change it.

**Comment by ghefraim** [comment]
I think he s referring to the white line of 1 pixel below it

**Comment by ghefraim** [comment]
I made the video a bit bigger, I think that impacted it? Idk for sure. Maybe we can revert to the original size

**Comment by ddardistrugatoru** [comment]
im referrin' to the video but if you said about the white line, then you can do it too

**Comment by ghefraim** [comment]
1. About the video - we'll let it as is
2. About the 1px line - we'll have to see after launch what we can do @DenisWithOneN . Right now I'm having other priorities
3. About the FAQ section, I will make one row of them, insread of 2

For the last 2 issues, I'm creating tickets
