### ISSUE TITLE
[Signup] Test different signup cases

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#42]
You need to perform actions like normal users would.
Firstly, you need to test 2 things:
- [x] new user
- [x] user that was already authenticated in previous camp (this should get details auto-filled)

### After you do these actions in the UI, please check the _database_, _auth_ system and _storage_. 
- These systems should contain the data related to the newly created users.
- I will give you permissions privately, to access these systems in the _firebase console_

Proposals about making the User Experience better are welcome to be discussed.

~Also please  check the admins dashboard to contain the data with all the users that signed up~ (this has not yet beed implemented)

**Comment by ghefraim** [comment]
Feedback after testing:
- [ ] Add validation for the checkboxes too
- [ ] Autofill data only based on email
- [ ] Do not autofill age and transport
- [ ] Remove default value on transport

I will let you know once i fix these, and can be retested.

**Comment by ghefraim** [comment]
@ddardistrugatoru I made the proposed changes. Please pull the last version of main, and let me know if there's still something wrong.
To recap, here's the things that need to be tested

- [ ] new user
- [ ] user that was already authenticated in previous camp (this should get details auto-filled)
- - [ ] should happen right after email, not after name input 
- - [ ] do not autofill age and transport
- [ ] checkboxes should be validated (user can't go next if there's no input)
- [ ] remove default check on transport

**Comment by ddardistrugatoru** [comment]
Yep, now all runs smooth and as it should. No corrections needed.
