### ISSUE TITLE
[Register] Add max character limits to input fields

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#46]
Add a max character limits to text input fields of maximum 32 characters

**Comment by ghefraim** [comment]
Added some restrictions to the length of text/number input.
Coding done.

**Comment by ddardistrugatoru** [comment]
Age verification works perfectly, if you want you can make the length input on 2, but it s okay. 
Name input it s okay
Phone number you can't do much here, as it is now it s perfect.

**Comment by ghefraim** [comment]
Yeah, the number input (age) can't be limited as the other ones apparently. I tried, but this way still works.
