### ISSUE TITLE
[Account] Implement see my details

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#48]

**Comment by ghefraim** [comment]
Coding done. @ddardistrugatoru please test this

**Comment by ghefraim** [comment]
Testing instructions:
Precodintion: user is logged in
Reproduce: On the '/cont' page press the 'vezi detaliile mele' button. The correct details for the user should appear on the bottom.

**Comment by ddardistrugatoru** [comment]
Works good, no issues found.
