### ISSUE TITLE
[Reset] *Bug* Reset password is not working

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#59]
Problem when resetting password -> when you solve it change the Log In text with Request Change or somethin' like that
![image](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/cfde0248-3ebb-4de9-90e5-2fff206b06d5)

**Comment by ghefraim** [comment]
Coding done. Can be tested @ddardistrugatoru

**Comment by ghefraim** [comment]
# Testing instructions
Precondition: user is logged out.
1. Click on Reset password. 
2. On the page, enter your email address. 
3. An email should be sent to that address with a link to change the password. 
4. Go to the link and change the password
5. Log back in with the new password (from the login page)

**Comment by ddardistrugatoru** [comment]
The reset works good but there is one problem, after you entered the email and you ve sent the mail it s freezin' the email which is a bad thing
Probably on phone most of them will misspell a letter or idk, it should let you change after the reset not reloadin the page and after the reload to re-enter the correct mail

**Comment by ddardistrugatoru** [comment]
Last thing to do -> after you get the password reset it should appear an redirect "Inapoi la Login"

**Comment by ghefraim** [comment]
> Last thing to do -> after you get the password reset it should appear an redirect "Inapoi la Login"

done

**Comment by ddardistrugatoru** [comment]
Perfect, nice work. It's working as it should.
