### ISSUE TITLE
[Login] *Bug* Unauthenticated email freezes the UI

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#60]
When i try to  log-in with an account that doesn't exist in the database the log-in button gets blocked and i can't do anythin', it should return an message like "account doesn't exist"

![image](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/161e757d-66d7-4eca-beb1-04051431d74b)

**Comment by ddardistrugatoru** [comment]
The reset works ok but there is one problem, after you entered the email and you ve sent the mail it s freezin' the email which is a bad thing
Probably on phone most of them will misspell a letter or idk, it should let you change after the reset not reloadin the page and after the reload to re-enter the correct mail 
![image](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/6f7238b3-71e1-4be1-bb02-b2befe403c35)

**Comment by ghefraim** [comment]
Coding done. Can be retested

**Comment by ddardistrugatoru** [comment]
Works good.
