### ISSUE TITLE
[Register]  Confirmation page dynamic based on age and date

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#63]

**Comment by ghefraim** [comment]
# Here's what I did:
In the agreement page (3rd step in Register) I added some new text.
The text depends on some factors:
- Age
- - if the user is >= 18 yrs old, nothing new appears
- - if the user is < 18 yrs old, a new text specific to <18 will appear
- Date range picked (start date and end date)
- - if the user has selected that he stays full-time (all 5 days) - a message with whole tax is displayed
- - if the user selected fewer days, a message with the daily tax is displayed (150 ron per day)

**Comment by ddardistrugatoru** [comment]
All the things that you told me are displaying correctly
Some things you can do ( probably ) -> If you select like i ll stay for 3 days to display the correct amount of money 150x3
For the "Regulament" thing if you are < 18 -> you can make an boolean for the "Inscrie-te" button if the user downloaded the Document set it on true so he can register if not freeze the button

**Comment by ghefraim** [comment]
1st thing you said - I was thinking the same. Will do it in 2 minutes.
2nd thing - it can also be downloaded from the home page. So it's not really justified, since the user can already have had downloaded it at that point. (From experience, we most of the time give them the paper in the camp cause they forget to print and sign it :D )

**Comment by ghefraim** [comment]
> If you select like i ll stay for 3 days to display the correct amount of money 150x3

Done.

**Comment by ddardistrugatoru** [comment]
yep, probably it s a wastin of time thing but probably most of them will never take a look at it on the homepage.. at least when they register they will be forced to take it and probably will arouse their interest on it

**Comment by ghefraim** [comment]
I will ask the business (Adelin XD) what's best in this situation. Until further notice, I'm closing the issue.
