### ISSUE TITLE
[Admins] Add account and logout buttons

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#67]
AdminsDashboard should have 2 new buttons in the sidebar: 'Cont' and 'Logout'

**Comment by ghefraim** [comment]
Done. Can be tested locally (not on prod)

**Comment by ddardistrugatoru** [comment]
The buttons are displayed only on "Mesaje, Admins, Statistici" page
![image](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/36e6d28b-8991-456f-b0bb-b6dcae3b678d)
![image](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/3227e4d9-20b6-44a5-84b0-1cc08596cf30)

**Comment by ghefraim** [comment]
you have to scroll to the most bottom point to see them XD

**Comment by ddardistrugatoru** [comment]
a nvm, forgot about it XDD

**Comment by ddardistrugatoru** [comment]
Works.
