### ISSUE TITLE
[Register] Prevent multiple clicking on the submit button

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#68]
add a state to know when the proccess of form submission is ongoing. In that time, the button should be disabled

**Comment by ghefraim** [comment]
also try to fix this comment:


// TODO: Fix bug when agreement is not checked, the button should still be visible
            // with different color, but it's not visible at all at this moment

**Comment by ghefraim** [comment]
# Testing instructions
While registering, try to click multiple times on the "Inscrie-te" button. You will see that's not possible (it was possible before). Nothing happens => this bug is fixed

**Comment by ddardistrugatoru** [comment]
Works good. I tried 2 times to spam it and now it's directly redirectin' to home logged in
