### ISSUE TITLE
[Account] *Bug* background visual bug

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#73]
When the FormCard is too big (for example you press 'Vezi datele mele' on /cont page), the background runs out and white is displayed:

![Image](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/92709351/dfcbf15a-af73-41ac-a25a-e6c38a99f92d)

**Comment by ghefraim** [comment]
Fixed.
Though I could not reproduce this on my 2k monitor. I had to manually make the Card bigger. What 8k monitor do you use? XDD

**Comment by ddardistrugatoru** [comment]
Works.
