### ISSUE TITLE
[Admins] *Bug* when expanding 2 rows

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#74]
When you try to get more infos from 2 users with one opened and one to be opened
https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/6c791fbe-8ee8-43d7-b84f-2bb7828b5404

**Comment by ghefraim** [comment]
coding done

**Comment by ddardistrugatoru** [comment]
Working.
