### ISSUE TITLE
[Admins] *Bug* when adding admins

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#75]
After i added an admin,randomly i pressed CTRL + Y / CTRL + Z and it s addin in that array one user ( even if i type somethin in the input of add admins it s updating the list +1 )
https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/8fd212f6-abb3-40ed-955c-e5d2d4cb51d3

**Comment by ghefraim** [comment]
Fixed.

**Comment by ddardistrugatoru** [comment]
Working.
One more thing that you can do, after you add / remove an admin to empty the input automatically

**Comment by ghefraim** [comment]
Done
