### ISSUE TITLE
[Admins] *Bug* removing a SuperAdmin

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#76]
https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/4795795e-5f05-47a2-860b-91f2073d3468

When i try as a SuperAdmin to remove an SuperAdmin it appers that he's removed but after the refresh he remains in the list. ( it happens for the admins too )

**Comment by ghefraim** [comment]
@ddardistrugatoru Can you see if you can reproduce this bug? Cause I can't. It successfully removes the admin and superAdmin. (from ths list after refresh, and even in DB)

**Comment by ddardistrugatoru** [comment]
> @ddardistrugatoru Can you see if you can reproduce this bug? Cause I can't. It successfully removes the admin and superAdmin. (from ths list after refresh, and even in DB)

It was from the browser again sadly
