### ISSUE TITLE
*Bug* Navigating in a new tab results in error

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#77]
Steps to reproduce:
!!!!! ONLY ON PRODUCTION SITE, NOT ON LOCAL ENV
1. Go to home page hopecamp.ro
2. Press on a button with CTRL (or command) or right click > open in new tab

![Image](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/92709351/61f3f009-6e58-4437-b719-9dd37bc2b2c3)

4. The newly opened page is not found

![Image](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/92709351/06144cf8-fa2b-4602-94e0-edabcfdc3aa9)

**Comment by ghefraim** [comment]
This has been fixed. (The bug was only on the deployed site hopecamp.ro , not locally)

**Comment by ddardistrugatoru** [comment]
Right now it s working ok, the only thing that first "Inscrie-te" button it's redirectin' to login page and the last two buttons to the register page.

**Comment by ghefraim** [comment]
@DenisWithOneN can fix that in his next PR

**Comment by DenisWithOneN** [comment]
I managed to fix the issue. Also i used the paths from constants folder as you suggested @ghefraim

**Comment by ddardistrugatoru** [comment]
works .
