### ISSUE TITLE
[Admins] Users table - Add filter by any column

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#79]
IN the admins dashboard > user list > add more filter capabilities

**Comment by ghefraim** [comment]
I added multiple columns to the filter that we had (we only had filtering by name).

This is now a bit limited, but I'm pretty sure it's enough for what the admins need.

I created a ticket that will add more options to this feature #80

**Comment by ddardistrugatoru** [comment]
Each filter works correctly.
