### ISSUE TITLE
[Admins] Add stats

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#81]

**Comment by ghefraim** [comment]
Added some stats in admins dashboard. 
Feedback is welcome.

**Comment by ddardistrugatoru** [comment]
Looks really nice, what you can do is to make a statistic for the people which are comin' for 5 days / 4 days and so on, to be something like
"Zile de participare idk" 5 Zile -> 100 Persoane / 4 Zile -> 15  Persoane
