### ISSUE TITLE
[Home] Make the line spacing bigger

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#88]
Make the line spacing a bit bigger
I suggest modifying the text-md, etc. These properties also contian line spacing, and can be tweaked to be a bit bigger

**Comment by DenisWithOneN** [comment]
If you're talking about the space between phrases we can use Line Height instead with leading: https://tailwindcss.com/docs/line-height

**Comment by ghefraim** [comment]
I tried doing that

But it gets overridden by md:text-md (depending of the screen size)

Thats what i was referring to: text-md and other sizes have this property included in it
