### ISSUE TITLE
[Home] *bug* Solve the white 1 pixel

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#93]
![Image](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/92709351/1fc01acc-cb4c-4453-9ea4-556daeaa256d)

**Comment by ghefraim** [comment]
@ddardistrugatoru is this still reproductible?

**Comment by ddardistrugatoru** [comment]
yes. for me it s the same

**Comment by DenisWithOneN** [comment]
I removed the wave section dividers since they are a pain to work with. We can come back to this later if we decide to go with them in the future but that's unlikely
