### ISSUE TITLE
[Home] Mobile slidebar visual problem

### ISSUE THREAD

**Issue by ddardistrugatoru** [tineret-spearanta-oradea/hopecamp-website#94]
If you're goin' to open the slidebar on mobile the countdown remains visible, it s not hiding.

![WhatsApp Image 2024-05-08 at 22 54 28_48f919d2](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/8aa9faf5-4961-4bd7-bb21-1632799de205)

**Comment by ghefraim** [comment]
done

**Comment by ddardistrugatoru** [comment]
fixed.
