### ISSUE TITLE
[Admin] Filter input bug

### ISSUE THREAD

**Issue by ddardistrugatoru** [tineret-spearanta-oradea/hopecamp-website#95]
If you want to search for an email for example it s gonna find what you re looking for but it s not resettin the page if your input it s clear
It remains bugged with the persons that you wanted to look for or empty if it didnt find it
https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/ea1cdad8-a4e3-42a7-9342-3446a8fa311d

**Comment by ghefraim** [comment]
@ddardistrugatoru coding done. can be tested on live website

**Comment by ddardistrugatoru** [comment]
working
