### ISSUE TITLE
Handle full occupancy

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#99]
When trying to register, but we hit full occupancy (should be set as a constant bool or something), we should show a message saying that the camp is full, and not let the user register.

We should also have a "hidden" link that can be used for people that we know of, after the full occupancy is hit. For example, in the past I've used 'hopecamp.ro/inscrie-te?mode=temp'. We can use the same thing (url parameter).

**Comment by ghefraim** [comment]
The coding is done. It's just a switch that can be turned on when getting asked by Adelin

**Comment by MaxiFrancis** [comment]
It is also too much behind. I do not know how to test id. 🙃

**Comment by ghefraim** [comment]
It's all good here, I will close this ticket. 
I will clean this ticket board and prioritize issues later this week
